version: "3.3"
services:
  subspace:
   build: .
   container_name: subspace
   restart: always
   volumes: 
    - wireguarddata:/data
   ports:
     - 8095:8095
   environment:
    - SUBSPACE_HTTP_HOST=localhost
    - SUBSPACE_LETSENCRYPT=true
    - SUBSPACE_HTTP_INSECURE=false
    - SUBSPACE_HTTP_ADDR=":80"
    - SUBSPACE_NAMESERVER=1.1.1.1
    - SUBSPACE_LISTENPORT=51820
    - SUBSPACE_IPV4_POOL=10.99.97.0/24
    - SUBSPACE_IPV6_POOL=fd00::10:97:0/64
    - SUBSPACE_IPV4_GW=10.99.97.1
    - SUBSPACE_IPV6_GW=fd00::10:97:1
    - SUBSPACE_IPV6_NAT_ENABLED=1

volumes:
  wireguarddata:
